language: ruby
rvm:
  - 1.8.7
script: "rake erb && rake syntax && rake style"
branches:
  only:
    - master
notifications:
  email:
    - craig@cwatson.org
gemfile: .gemfile
env:
  - PUPPET_VERSION=3.1.1        # latest 3.1
  - PUPPET_VERSION=3.0.1        # latest 3.0
